language: go
env: GO111MODULE=on
go:
  - 1.13.x
script:
  - make releases

deploy:
  provider: releases
  skip_cleanup: true
  github_token: ${GITHUB_TOKEN} # Set in travis-ci.org dashboard
  file: bin/*
  on:
    tags: true