os: linux
language: go
env: GO111MODULE=on
go:
  - 1.13.x
script:
  - echo ${GITHUB_TOKEN}
#  - make releases

deploy:
  provider: releases
  cleanup: true
  api_key: $GITHUB_TOKEN
  file: bin/*
  on:
    tags: true