os: linux
language: go
env: GO111MODULE=on
go:
  - 1.13.x
script:
  - go mod tidy
  - make releases

deploy:
  provider: releases
  cleanup: false
  token: $GITHUB_TOKEN
  file: bin/*
  on:
    tags: true